version: '3.8'
services:
  php:
    build:
      context: ../../
      dockerfile: ./Service/Docker/Dockerfile
    command: sh /run/run-php-dev.sh
    container_name: "xguard-service-bot-php"
    depends_on:
      - database
    environment:
      TZ: "Europe/London"
    env_file:
      - ../../App/.env
      - ../../App/.env.local
      - .env
      - .env.local
    networks:
      service-bot-network:
    restart: always
    tty: true
    volumes:
      - ../../App:/app:cached
      - ../php.d/99-projects.ini:/usr/local/etc/php/conf.d/99-projects.ini:ro
      - ../../App/var/composer/cache/:/root/.composer/cache/:delegated
      - ../run/run-php-dev.sh:/run/run-php.sh:delegated
      - ~/.ssh/:/root/.ssh/
      - ~/.ssh/:/home/www/.ssh/

  database:
    command: postgres -c 'max_connections=200'
    container_name: "xguard-service-bot-database"
    environment:
      TZ: "Europe/London"
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
      - .env.local
    image: postgres:latest
    networks:
      service-bot-network:
        aliases:
          - ${DATABASE_HOST}
      service-bot-database-network:
        aliases:
          - ${DATABASE_HOST}
    ports:
      - 5434:5432
    restart: always
    shm_size: 1g
    tty: true
    volumes:
      - ../postgres/data:/var/lib/postgresql/data:delegated

networks:
  service-bot-database-network:
    name: xguard-service-bot-database-network
  service-bot-network:
    name: xguard-service-bot-network
    external: true
