table_storage:
  table_name: doctrine_migration_versions
  version_column_name: version
  version_column_length: 1024
  executed_at_column_name: executed_at
  execution_time_column_name: execution_time

migrations_paths:
  'XGuard\Bot\Facebook\Infrastructure\Doctrine\DBAL\Migrations': src/Facebook/Infrastructure/Doctrine/DBAL/Migrations
  'XGuard\Bot\Shared\Infrastructure\Doctrine\DBAL\Migrations': src/Shared/Infrastructure/Doctrine/DBAL/Migrations
  'XGuard\Bot\Telegram\Infrastructure\Doctrine\DBAL\Migrations': src/Telegram/Infrastructure/Doctrine/DBAL/Migrations

all_or_nothing: true
check_database_platform: true
organize_migrations: none
