<?php declare(strict_types=1);

namespace Test\XGuard\Bot\Facebook\Domain\DTO;

use DateInterval;
use DateTime;
use Error;
use Exception;
use JsonException;
use PHPUnit\Framework\TestCase;
use XGuard\Bot\Facebook\Application\Service\DTOFactoryService;
use XGuard\Bot\Facebook\Domain\Enum\SupportedPlatformsEnum;

/**
 *
 */
final class ApplicationDTOTest extends TestCase
{

    /**
     * @return array[]
     * @throws Exception
     */
    public function dataProvider(): array
    {
        return [
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => (new DateTime())->add(
                        new DateInterval('P'.random_int(51, 90).'M')
                    )->getTimestamp(),
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'WEB',//SupportedPlatformsEnum::WEB
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'CANVAS',//SupportedPlatformsEnum::CANVAS
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'MOBILE_WEB',//SupportedPlatformsEnum::MOBILE_WEB
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'IPHONE',//SupportedPlatformsEnum::IPHONE
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'IPAD',//SupportedPlatformsEnum::IPAD
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'ANDROID',//SupportedPlatformsEnum::ANDROID
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'WINDOWS',//SupportedPlatformsEnum::WINDOWS
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'AMAZON',//SupportedPlatformsEnum::AMAZON
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'SUPPLEMENTARY_IMAGES',
                    //SupportedPlatformsEnum::SUPPLEMENTARY_IMAGES
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'GAMEROOM',//SupportedPlatformsEnum::GAMEROOM
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'INSTANT_GAME',//SupportedPlatformsEnum::INSTANT_GAME
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'OCULUS',//SupportedPlatformsEnum::OCULUS
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'SAMSUNG',//SupportedPlatformsEnum::SAMSUNG
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'XIAOMI',//SupportedPlatformsEnum::XIAOMI
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => null,
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                '',
            ],
            [
                [
                    'id'                                     => 'id',
                    'aam_rules'                              => null,
                    'an_ad_space_limit'                      => null,
                    'an_platforms'                           => null,
                    'app_domains'                            => null,
                    'app_events_config'                      => null,
                    'app_install_tracked'                    => null,
                    'app_name'                               => null,
                    'app_signals_binding_ios'                => null,
                    'app_type'                               => null,
                    'auth_dialog_data_help_url'              => null,
                    'auth_dialog_headline'                   => null,
                    'auth_dialog_perms_explanation'          => null,
                    'auth_referral_default_activity_privacy' => null,
                    'auth_referral_enabled'                  => null,
                    'auth_referral_extended_perms'           => null,
                    'auth_referral_friend_perms'             => null,
                    'auth_referral_response_type'            => null,
                    'auth_referral_user_perms'               => null,
                    'canvas_fluid_height'                    => null,
                    'canvas_fluid_width'                     => null,
                    'canvas_url'                             => null,
                    'category'                               => 'category',
                    'client_config'                          => null,
                    'company'                                => null,
                    'configured_ios_sso'                     => null,
                    'contact_email'                          => null,
                    'created_time'                           => null,
                    'creator_uid'                            => null,
                    'daily_active_users'                     => null,
                    'daily_active_users_rank'                => null,
                    'deauth_callback_url'                    => null,
                    'default_share_mode'                     => null,
                    'description'                            => 'description',
                    'financial_id'                           => null,
                    'hosting_url'                            => null,
                    'icon_url'                               => null,
                    'ios_bundle_id'                          => null,
                    'ios_supports_native_proxy_auth_flow'    => null,
                    'ios_supports_system_auth'               => null,
                    'ipad_app_store_id'                      => null,
                    'iphone_app_store_id'                    => null,
                    'latest_sdk_version'                     => null,
                    'link'                                   => 'https://fb.me/',
                    'logging_token'                          => null,
                    'logo_url'                               => null,
                    'migrations'                             => null,
                    'mobile_profile_section_url'             => null,
                    'mobile_web_url'                         => null,
                    'monthly_active_users'                   => null,
                    'monthly_active_users_rank'              => null,
                    'name'                                   => 'name',
                    'namespace'                              => 'namespace',
                    'object_store_urls'                      => null,
                    'page_tab_default_name'                  => null,
                    'page_tab_url'                           => null,
                    'photo_url'                              => null,
                    'privacy_policy_url'                     => null,
                    'profile_section_url'                    => null,
                    'property_id'                            => null,
                    'real_time_mode_devices'                 => null,
                    'restrictions'                           => null,
                    'restrictive_data_filter_params'         => null,
                    'secure_canvas_url'                      => null,
                    'secure_page_tab_url'                    => null,
                    'server_ip_whitelist'                    => null,
                    'social_discovery'                       => null,
                    'subcategory'                            => null,
                    'suggested_events_setting'               => null,
                    'supported_platforms'                    => 'XIAOMI1',//SupportedPlatformsEnum::XIAOMI1?
                    'terms_of_service_url'                   => null,
                    'url_scheme_suffix'                      => null,
                    'user_support_email'                     => null,
                    'user_support_url'                       => null,
                    'website_url'                            => null,
                    'weekly_active_users'                    => null,
                ],
                Error::class,
            ],
        ];
    }

    /**
     * @param array  $data
     * @param string $exception
     *
     * @return void
     * @throws JsonException
     * @dataProvider dataProvider
     */
    public function testConstruct(array $data, string $exception): void
    {
        if (!empty($exception)) {
            $this->expectException($exception);
        }

        $DTOFactoryService = new DTOFactoryService();

        self::assertNull($DTOFactoryService->createDTOFromApplication(null));

        $applicationDTO = $DTOFactoryService->createDTOFromApplication($data);

        self::assertIsObject($applicationDTO);
        self::assertEquals($data['id'], $applicationDTO->id);
        self::assertEquals($data['aam_rules'], $applicationDTO->aam_rules);
        self::assertEquals($data['an_ad_space_limit'], $applicationDTO->an_ad_space_limit);
        self::assertEquals($data['an_platforms'], $applicationDTO->an_platforms);
        self::assertEquals($data['app_domains'], $applicationDTO->app_domains);
        self::assertEquals($data['app_events_config'], $applicationDTO->app_events_config);
        self::assertEquals($data['app_install_tracked'], $applicationDTO->app_install_tracked);
        self::assertEquals($data['app_name'], $applicationDTO->app_name);
        self::assertEquals($data['app_signals_binding_ios'], $applicationDTO->app_signals_binding_ios);
        self::assertEquals($data['app_type'], $applicationDTO->app_type);
        self::assertEquals($data['auth_dialog_data_help_url'], $applicationDTO->auth_dialog_data_help_url);
        self::assertEquals($data['auth_dialog_headline'], $applicationDTO->auth_dialog_headline);
        self::assertEquals($data['auth_dialog_perms_explanation'], $applicationDTO->auth_dialog_perms_explanation);
        self::assertEquals(
            $data['auth_referral_default_activity_privacy'],
            $applicationDTO->auth_referral_default_activity_privacy
        );
        self::assertEquals($data['auth_referral_enabled'], $applicationDTO->auth_referral_enabled);
        self::assertEquals($data['auth_referral_extended_perms'], $applicationDTO->auth_referral_extended_perms);
        self::assertEquals($data['auth_referral_friend_perms'], $applicationDTO->auth_referral_friend_perms);
        self::assertEquals($data['auth_referral_response_type'], $applicationDTO->auth_referral_response_type);
        self::assertEquals($data['auth_referral_user_perms'], $applicationDTO->auth_referral_user_perms);
        self::assertEquals($data['canvas_fluid_height'], $applicationDTO->canvas_fluid_height);
        self::assertEquals($data['canvas_fluid_width'], $applicationDTO->canvas_fluid_width);
        self::assertEquals($data['canvas_url'], $applicationDTO->canvas_url);
        self::assertEquals($data['category'], $applicationDTO->category);
        self::assertEquals($data['client_config'], $applicationDTO->client_config);
        self::assertEquals($data['company'], $applicationDTO->company);
        self::assertEquals($data['configured_ios_sso'], $applicationDTO->configured_ios_sso);
        self::assertEquals($data['contact_email'], $applicationDTO->contact_email);
        self::assertEquals($data['created_time'], $applicationDTO->created_time?->getTimestamp());
        self::assertEquals($data['creator_uid'], $applicationDTO->creator_uid);
        self::assertEquals($data['daily_active_users'], $applicationDTO->daily_active_users);
        self::assertEquals($data['daily_active_users_rank'], $applicationDTO->daily_active_users_rank);
        self::assertEquals($data['deauth_callback_url'], $applicationDTO->deauth_callback_url);
        self::assertEquals($data['default_share_mode'], $applicationDTO->default_share_mode);
        self::assertEquals($data['description'], $applicationDTO->description);
        self::assertEquals($data['financial_id'], $applicationDTO->financial_id);
        self::assertEquals($data['hosting_url'], $applicationDTO->hosting_url);
        self::assertEquals($data['icon_url'], $applicationDTO->icon_url);
        self::assertEquals($data['ios_bundle_id'], $applicationDTO->ios_bundle_id);
        self::assertEquals(
            $data['ios_supports_native_proxy_auth_flow'],
            $applicationDTO->ios_supports_native_proxy_auth_flow
        );
        self::assertEquals($data['ios_supports_system_auth'], $applicationDTO->ios_supports_system_auth);
        self::assertEquals($data['ipad_app_store_id'], $applicationDTO->ipad_app_store_id);
        self::assertEquals($data['iphone_app_store_id'], $applicationDTO->iphone_app_store_id);
        self::assertEquals($data['latest_sdk_version'], $applicationDTO->latest_sdk_version);
        self::assertEquals($data['link'], $applicationDTO->link);
        self::assertEquals($data['logging_token'], $applicationDTO->logging_token);
        self::assertEquals($data['logo_url'], $applicationDTO->logo_url);
        self::assertEquals($data['migrations'], $applicationDTO->migrations);
        self::assertEquals($data['mobile_profile_section_url'], $applicationDTO->mobile_profile_section_url);
        self::assertEquals($data['mobile_web_url'], $applicationDTO->mobile_web_url);
        self::assertEquals($data['monthly_active_users'], $applicationDTO->monthly_active_users);
        self::assertEquals($data['monthly_active_users_rank'], $applicationDTO->monthly_active_users_rank);
        self::assertEquals($data['name'], $applicationDTO->name);
        self::assertEquals($data['namespace'], $applicationDTO->namespace);
        self::assertEquals($data['object_store_urls'], $applicationDTO->object_store_urls);
        self::assertEquals($data['page_tab_default_name'], $applicationDTO->page_tab_default_name);
        self::assertEquals($data['page_tab_url'], $applicationDTO->page_tab_url);
        self::assertEquals($data['photo_url'], $applicationDTO->photo_url);
        self::assertEquals($data['privacy_policy_url'], $applicationDTO->privacy_policy_url);
        self::assertEquals($data['profile_section_url'], $applicationDTO->profile_section_url);
        self::assertEquals($data['property_id'], $applicationDTO->property_id);
        self::assertEquals($data['real_time_mode_devices'], $applicationDTO->real_time_mode_devices);
        self::assertEquals($data['restrictions'], $applicationDTO->restrictions);
        self::assertEquals($data['restrictive_data_filter_params'], $applicationDTO->restrictive_data_filter_params);
        self::assertEquals($data['secure_canvas_url'], $applicationDTO->secure_canvas_url);
        self::assertEquals($data['secure_page_tab_url'], $applicationDTO->secure_page_tab_url);
        self::assertEquals($data['server_ip_whitelist'], $applicationDTO->server_ip_whitelist);
        self::assertEquals($data['social_discovery'], $applicationDTO->social_discovery);
        self::assertEquals($data['subcategory'], $applicationDTO->subcategory);
        self::assertEquals($data['suggested_events_setting'], $applicationDTO->suggested_events_setting);

        if (null !== $data['supported_platforms']) {
            self::assertEquals(
                constant((SupportedPlatformsEnum::class).'::'.$data['supported_platforms']),
                $applicationDTO->supported_platforms
            );
        } else {
            self::assertEquals($data['supported_platforms'], $applicationDTO->supported_platforms);
        }

        self::assertEquals($data['terms_of_service_url'], $applicationDTO->terms_of_service_url);
        self::assertEquals($data['url_scheme_suffix'], $applicationDTO->url_scheme_suffix);
        self::assertEquals($data['user_support_email'], $applicationDTO->user_support_email);
        self::assertEquals($data['user_support_url'], $applicationDTO->user_support_url);
        self::assertEquals($data['website_url'], $applicationDTO->website_url);
        self::assertEquals($data['weekly_active_users'], $applicationDTO->weekly_active_users);
        self::assertNotEmpty(json_encode($applicationDTO, JSON_THROW_ON_ERROR));
    }
}
