<?php declare(strict_types=1);

namespace Test\XGuard\Bot\Facebook\Domain\DTO;

use DateInterval;
use DateTime;
use Error;
use Exception;
use JsonException;
use PHPUnit\Framework\TestCase;
use XGuard\Bot\Facebook\Application\Service\DTOFactoryService;
use XGuard\Bot\Facebook\Domain\Enum\CategoryEventEnum;
use XGuard\Bot\Facebook\Domain\Enum\OnlineEventFormatEnum;
use XGuard\Bot\Facebook\Domain\Enum\TypeEventEnum;

/**
 *
 */
final class EventDTOTest extends TestCase
{

    /**
     * @return array[]
     * @throws Exception
     */
    public function dataProvider(): array
    {
        return [
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'CLASSIC_LITERATURE',//CategoryEventEnum::CLASSIC_LITERATURE
                    'cover'                        => null,
                    'created_time'                 => (new DateTime())->add(
                        new DateInterval('P'.random_int(0, 50).'M')
                    )->getTimestamp(),
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => 'messenger_room',//OnlineEventFormatEnum::messenger_room
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => 'private',//TypeEventEnum::private
                    'updated_time'                 => (new DateTime())->add(
                        new DateInterval('P'.random_int(51, 90).'M')
                    )->getTimestamp(),
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'COMEDY',//CategoryEventEnum::COMEDY
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => 'third_party',//OnlineEventFormatEnum::third_party
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => 'public',//TypeEventEnum::public
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'CRAFTS',//CategoryEventEnum::CRAFTS
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => 'fb_live',//OnlineEventFormatEnum::fb_live
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => 'group',//TypeEventEnum::group
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'DANCE',//CategoryEventEnum::DANCE
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => 'other',//OnlineEventFormatEnum::other
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => 'community',//TypeEventEnum::community
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'DRINKS',//CategoryEventEnum::DRINKS
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => 'none',//OnlineEventFormatEnum::none
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => 'friends',//TypeEventEnum::friends
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'FITNESS_AND_WORKOUTS',//CategoryEventEnum::FITNESS_AND_WORKOUTS
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => 'work_company',//TypeEventEnum::work_company
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'FOODS',//CategoryEventEnum::FOODS
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'GAMES',//CategoryEventEnum::GAMES
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'GARDENING',//CategoryEventEnum::GARDENING
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'HEALTH_AND_MEDICAL',//CategoryEventEnum::HEALTH_AND_MEDICAL
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'HEALTHY_LIVING_AND_SELF_CARE',
                    //CategoryEventEnum::HEALTHY_LIVING_AND_SELF_CARE
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'HOME_AND_GARDEN',//CategoryEventEnum::HOME_AND_GARDEN
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'MUSIC_AND_AUDIO',//CategoryEventEnum::MUSIC_AND_AUDIO
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'PARTIES',//CategoryEventEnum::PARTIES
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'PROFESSIONAL_NETWORKING',
                    //CategoryEventEnum::PROFESSIONAL_NETWORKING
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'RELIGIONS',//CategoryEventEnum::RELIGIONS
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'SHOPPING_EVENT',//CategoryEventEnum::SHOPPING_EVENT
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'SOCIAL_ISSUES',//CategoryEventEnum::SOCIAL_ISSUES
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'SPORTS',//CategoryEventEnum::SPORTS
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'THEATER',//CategoryEventEnum::THEATER
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'TV_AND_MOVIES',//CategoryEventEnum::TV_AND_MOVIES
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'VISUAL_ARTS',//CategoryEventEnum::VISUAL_ARTS
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => null,
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                '',
            ],
            [
                [
                    'id'                           => null,
                    'attending_count'              => null,
                    'can_guests_invite'            => null,
                    'category'                     => 'VISUAL_ARTS1',//CategoryEventEnum::VISUAL_ARTS1?
                    'cover'                        => null,
                    'created_time'                 => null,
                    'declined_count'               => null,
                    'description'                  => 'description',
                    'discount_code_enabled'        => null,
                    'end_time'                     => 'end_time',
                    'event_times'                  => [['event_time']],
                    'guest_list_enabled'           => null,
                    'interested_count'             => null,
                    'is_canceled'                  => null,
                    'is_draft'                     => null,
                    'is_online'                    => null,
                    'is_page_owned'                => null,
                    'maybe_count'                  => null,
                    'name'                         => 'name',
                    'noreply_count'                => null,
                    'online_event_format'          => null,
                    'online_event_third_party_url' => null,
                    'owner'                        => null,
                    'place'                        => null,
                    'scheduled_publish_time'       => null,
                    'start_time'                   => 'start_time',
                    'ticket_uri'                   => null,
                    'ticket_uri_start_sales_time'  => null,
                    'ticketing_privacy_uri'        => null,
                    'ticketing_terms_uri'          => null,
                    'timezone'                     => null,
                    'type'                         => null,
                    'updated_time'                 => null,
                ],
                Error::class,
            ],
        ];
    }

    /**
     * @param array  $data
     * @param string $exception
     *
     * @return void
     * @throws JsonException
     * @dataProvider dataProvider
     */
    public function testConstruct(array $data, string $exception): void
    {
        if (!empty($exception)) {
            $this->expectException($exception);
        }

        $DTOFactoryService = new DTOFactoryService();

        self::assertNull($DTOFactoryService->createDTOFromEvent(null));

        $eventDTO = $DTOFactoryService->createDTOFromEvent($data);

        self::assertIsObject($eventDTO);
        self::assertEquals($data['id'], $eventDTO->id);
        self::assertEquals($data['attending_count'], $eventDTO->attending_count);
        self::assertEquals($data['can_guests_invite'], $eventDTO->can_guests_invite);

        if (null !== $data['category']) {
            self::assertEquals(
                constant((CategoryEventEnum::class).'::'.$data['category']),
                $eventDTO->category
            );
        } else {
            self::assertEquals($data['category'], $eventDTO->category);
        }

        self::assertEquals($data['cover'], $eventDTO->cover);
        self::assertEquals($data['created_time'], $eventDTO->created_time?->getTimestamp());
        self::assertEquals($data['declined_count'], $eventDTO->declined_count);
        self::assertEquals($data['description'], $eventDTO->description);
        self::assertEquals($data['discount_code_enabled'], $eventDTO->discount_code_enabled);
        self::assertEquals($data['end_time'], $eventDTO->end_time);
        self::assertEquals(
            json_encode($data['event_times'], JSON_THROW_ON_ERROR),
            json_encode($eventDTO->event_times, JSON_THROW_ON_ERROR)
        );
        self::assertEquals($data['guest_list_enabled'], $eventDTO->guest_list_enabled);
        self::assertEquals($data['interested_count'], $eventDTO->interested_count);
        self::assertEquals($data['is_canceled'], $eventDTO->is_canceled);
        self::assertEquals($data['is_draft'], $eventDTO->is_draft);
        self::assertEquals($data['is_online'], $eventDTO->is_online);
        self::assertEquals($data['is_page_owned'], $eventDTO->is_page_owned);
        self::assertEquals($data['maybe_count'], $eventDTO->maybe_count);
        self::assertEquals($data['name'], $eventDTO->name);
        self::assertEquals($data['noreply_count'], $eventDTO->noreply_count);

        if (null !== $data['online_event_format']) {
            self::assertEquals(
                constant((OnlineEventFormatEnum::class).'::'.$data['online_event_format']),
                $eventDTO->online_event_format
            );
        } else {
            self::assertEquals($data['online_event_format'], $eventDTO->online_event_format);
        }

        self::assertEquals($data['online_event_third_party_url'], $eventDTO->online_event_third_party_url);
        self::assertEquals($data['owner'], $eventDTO->owner);
        self::assertEquals($data['place'], $eventDTO->place);
        self::assertEquals($data['scheduled_publish_time'], $eventDTO->scheduled_publish_time);
        self::assertEquals($data['start_time'], $eventDTO->start_time);
        self::assertEquals($data['ticket_uri'], $eventDTO->ticket_uri);
        self::assertEquals($data['ticket_uri_start_sales_time'], $eventDTO->ticket_uri_start_sales_time);
        self::assertEquals($data['ticketing_privacy_uri'], $eventDTO->ticketing_privacy_uri);
        self::assertEquals($data['ticketing_terms_uri'], $eventDTO->ticketing_terms_uri);
        self::assertEquals($data['timezone'], $eventDTO->timezone);

        if (null !== $data['type']) {
            self::assertEquals(
                constant((TypeEventEnum::class).'::'.$data['type']),
                $eventDTO->type
            );
        } else {
            self::assertEquals($data['type'], $eventDTO->type);
        }

        self::assertEquals($data['updated_time'], $eventDTO->updated_time?->getTimestamp());


        self::assertNotEmpty(json_encode($eventDTO, JSON_THROW_ON_ERROR));
    }
}
